---
# handlers file for app
- name: enable puma
  become: true
  systemd:
    name: puma
    enabled: true
  tags: app-tag

- name: reload puma
  become: true
  systemd:
    name: puma
    state: restarted
