---
- name: Configure hosts & deploy application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 10.130.0.25
  tasks:
    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify: restart mongod

    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: enable puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
      tags: app-tag
      notify: reload puma

  handlers:
    - name: restart mongod
      become: true
      service:
        name: mongod
        state: restarted
      tags: app-db

    - name: enable puma
      become: true
      systemd: name=puma enabled=yes
      tags: app-tag

    - name: reload puma
      become: true
      systemd: name=puma state=restarted
      tags: app-tag
